# backend/app/terminal_catalog.py
"""
Каталог инструментов и их флагов для режима «Конструктор» встроенного терминала.
Только метаданные — сборка строки команды выполняется на фронте, а фактический
запуск валидируется в terminal.py по ALLOWED_BINARIES.

Схема флага:
  {
    "flag": "--level",          # то, что подставляется в команду
    "label": "Уровень тестов",
    "description": "...",
    "type": "bool" | "text" | "choice" | "number",
    "choices": ["1","2",...],   # для type=choice
    "placeholder": "1-5",       # для text/number
    "default": "1",             # необязательно
    "group": "Обнаружение",     # для группировки в UI
  }
"""

TOOL_CATALOG = [
    {
        "id": "sqlmap",
        "name": "sqlmap",
        "binary": "sqlmap",
        "category": "web_vuln",
        "description": "Автоматическое обнаружение и эксплуатация SQL-инъекций.",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site/page.php?id=1"},
        "examples": [
            "sqlmap -u \"https://site/item.php?id=1\" --batch --level 2 --risk 2",
            "sqlmap -u \"https://site/login\" --data \"user=a&pass=b\" --batch --dbs",
        ],
        "flags": [
            {"flag": "--batch", "label": "Без вопросов (--batch)", "type": "bool", "default": "on",
             "description": "Не задавать интерактивных вопросов, брать ответы по умолчанию.", "group": "Общее"},
            {"flag": "--data", "label": "POST-данные", "type": "text", "placeholder": "id=1&name=x",
             "description": "Тело запроса; включает тестирование POST-параметров.", "group": "Запрос"},
            {"flag": "--cookie", "label": "Cookie", "type": "text", "placeholder": "PHPSESSID=...",
             "description": "Заголовок Cookie для аутентифицированных запросов.", "group": "Запрос"},
            {"flag": "--headers", "label": "Доп. заголовки", "type": "text", "placeholder": "X-API-Key: 123",
             "description": "Дополнительные HTTP-заголовки (через \\n).", "group": "Запрос"},
            {"flag": "-p", "label": "Тестировать параметр(ы)", "type": "text", "placeholder": "id,cat",
             "description": "Явно указать тестируемые параметры.", "group": "Запрос"},
            {"flag": "--level", "label": "Уровень", "type": "choice", "choices": ["1", "2", "3", "4", "5"], "default": "1",
             "description": "Глубина проверок (заголовки, cookie и т.д.). Выше — дольше.", "group": "Обнаружение"},
            {"flag": "--risk", "label": "Риск", "type": "choice", "choices": ["1", "2", "3"], "default": "1",
             "description": "Рискованность нагрузок (3 — потенциально изменяющие данные).", "group": "Обнаружение"},
            {"flag": "--technique", "label": "Техники", "type": "text", "placeholder": "BEUSTQ",
             "description": "Ограничить техники: B/E/U/S/T/Q.", "group": "Обнаружение"},
            {"flag": "--dbms", "label": "СУБД", "type": "choice",
             "choices": ["MySQL", "PostgreSQL", "Microsoft SQL Server", "Oracle", "SQLite"],
             "description": "Подсказать тип СУБД, чтобы ускорить обнаружение.", "group": "Обнаружение"},
            {"flag": "--dbs", "label": "Список БД", "type": "bool",
             "description": "Перечислить доступные базы данных.", "group": "Извлечение"},
            {"flag": "--tables", "label": "Список таблиц", "type": "bool",
             "description": "Перечислить таблицы (можно с -D <база>).", "group": "Извлечение"},
            {"flag": "--columns", "label": "Список столбцов", "type": "bool",
             "description": "Перечислить столбцы (с -D и -T).", "group": "Извлечение"},
            {"flag": "--dump", "label": "Выгрузить данные", "type": "bool",
             "description": "Выгрузить содержимое выбранной таблицы.", "group": "Извлечение"},
            {"flag": "-D", "label": "База (-D)", "type": "text", "placeholder": "app_db",
             "description": "Целевая база для --tables/--columns/--dump.", "group": "Извлечение"},
            {"flag": "-T", "label": "Таблица (-T)", "type": "text", "placeholder": "users",
             "description": "Целевая таблица для --columns/--dump.", "group": "Извлечение"},
            {"flag": "--current-user", "label": "Текущий пользователь", "type": "bool",
             "description": "Показать пользователя СУБД.", "group": "Извлечение"},
            {"flag": "--current-db", "label": "Текущая БД", "type": "bool",
             "description": "Показать имя текущей базы.", "group": "Извлечение"},
            {"flag": "--threads", "label": "Потоки", "type": "number", "placeholder": "1-10", "default": "1",
             "description": "Число параллельных запросов при извлечении.", "group": "Производительность"},
            {"flag": "--random-agent", "label": "Случайный User-Agent", "type": "bool",
             "description": "Подменять User-Agent случайным браузерным.", "group": "Обход"},
            {"flag": "--tamper", "label": "Tamper-скрипты", "type": "text", "placeholder": "space2comment,between",
             "description": "Скрипты обфускации нагрузок для обхода WAF.", "group": "Обход"},
            {"flag": "--proxy", "label": "Прокси", "type": "text", "placeholder": "http://127.0.0.1:8080",
             "description": "Пропускать трафик через прокси (Burp/ZAP).", "group": "Обход"},
        ],
    },
    {
        "id": "nmap",
        "name": "nmap",
        "binary": "nmap",
        "category": "recon",
        "description": "Сканер портов, сервисов, ОС и NSE-скриптов.",
        "target": {"kind": "host", "flag": "", "placeholder": "192.168.1.0/24 или host"},
        "examples": ["nmap -sV -sC -T4 scanme.nmap.org", "nmap -p- --min-rate 2000 10.0.0.5"],
        "flags": [
            {"flag": "-sS", "label": "SYN-скан", "type": "bool", "description": "Полускрытое сканирование (нужен root).", "group": "Тип"},
            {"flag": "-sT", "label": "TCP connect", "type": "bool", "description": "Полное TCP-подключение.", "group": "Тип"},
            {"flag": "-sU", "label": "UDP-скан", "type": "bool", "description": "Сканировать UDP-порты.", "group": "Тип"},
            {"flag": "-sn", "label": "Только ping", "type": "bool", "description": "Обнаружение хостов без портов.", "group": "Тип"},
            {"flag": "-p", "label": "Порты", "type": "text", "placeholder": "1-1000, 80,443 или -", "description": "Диапазон портов.", "group": "Область"},
            {"flag": "--top-ports", "label": "Top-N портов", "type": "number", "placeholder": "100", "description": "N самых частых портов.", "group": "Область"},
            {"flag": "-sV", "label": "Версии сервисов", "type": "bool", "description": "Определение версий служб.", "group": "Определение"},
            {"flag": "-O", "label": "Определение ОС", "type": "bool", "description": "TCP/IP fingerprinting ОС.", "group": "Определение"},
            {"flag": "-sC", "label": "Стандартные скрипты", "type": "bool", "description": "Набор NSE default.", "group": "Определение"},
            {"flag": "--script", "label": "NSE-скрипты", "type": "text", "placeholder": "vuln, http-*", "description": "Список/категории скриптов.", "group": "Определение"},
            {"flag": "-A", "label": "Агрессивно (-A)", "type": "bool", "description": "-sV -O -sC --traceroute разом.", "group": "Определение"},
            {"flag": "-T4", "label": "Тайминг T4", "type": "bool", "description": "Быстрый тайминг.", "group": "Производительность"},
            {"flag": "--min-rate", "label": "min-rate", "type": "number", "placeholder": "1000", "description": "Мин. пакетов/с.", "group": "Производительность"},
            {"flag": "-Pn", "label": "Без ping (-Pn)", "type": "bool", "description": "Считать хост живым, пропустить обнаружение.", "group": "Обход"},
            {"flag": "-v", "label": "Подробно (-v)", "type": "bool", "description": "Больше вывода.", "group": "Вывод"},
        ],
    },
    {
        "id": "nikto",
        "name": "nikto",
        "binary": "nikto",
        "category": "web_vuln",
        "description": "Сканер веб-сервера: опасные файлы, устаревшее ПО, мисконфигурации.",
        "target": {"kind": "url", "flag": "-h", "placeholder": "https://site"},
        "examples": ["nikto -h https://site -ssl", "nikto -h 10.0.0.5 -p 8080 -Tuning 1,2,3"],
        "flags": [
            {"flag": "-ssl", "label": "Форсировать SSL", "type": "bool", "description": "Использовать HTTPS.", "group": "Соединение"},
            {"flag": "-port", "label": "Порт(ы)", "type": "text", "placeholder": "80,443,8080", "description": "Порты цели.", "group": "Соединение"},
            {"flag": "-Tuning", "label": "Tuning", "type": "text", "placeholder": "1,2,3,b", "description": "Классы проверок (1=файлы, 2=misconfig, 9=SQLi...).", "group": "Проверки"},
            {"flag": "-timeout", "label": "Таймаут запроса", "type": "number", "placeholder": "10", "description": "Секунд на запрос.", "group": "Соединение"},
            {"flag": "-maxtime", "label": "Лимит времени", "type": "text", "placeholder": "10m", "description": "Максимум на сканирование.", "group": "Проверки"},
            {"flag": "-useragent", "label": "User-Agent", "type": "text", "placeholder": "Mozilla/5.0 ...", "description": "Подмена User-Agent.", "group": "Обход"},
            {"flag": "-nointeractive", "label": "Без интерактива", "type": "bool", "default": "on", "description": "Не задавать вопросов.", "group": "Проверки"},
        ],
    },
    {
        "id": "gobuster",
        "name": "gobuster (dir)",
        "binary": "gobuster",
        "category": "dirs",
        "description": "Брутфорс путей/файлов по словарю.",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site", "prefix_subcommand": "dir"},
        "examples": ["gobuster dir -u https://site -w /usr/share/wordlists/dirb/common.txt -x php,txt"],
        "flags": [
            {"flag": "-w", "label": "Словарь", "type": "text", "placeholder": "/usr/share/wordlists/dirb/common.txt",
             "description": "Путь к файлу словаря.", "group": "Словарь"},
            {"flag": "-x", "label": "Расширения", "type": "text", "placeholder": "php,txt,bak", "description": "Проверять с расширениями.", "group": "Словарь"},
            {"flag": "-t", "label": "Потоки", "type": "number", "placeholder": "20", "default": "20", "description": "Число потоков.", "group": "Производительность"},
            {"flag": "-s", "label": "Статусы", "type": "text", "placeholder": "200,204,301,302,307,401,403", "description": "Показывать только эти коды.", "group": "Фильтр"},
            {"flag": "-b", "label": "Скрыть статусы", "type": "text", "placeholder": "404", "description": "Игнорировать эти коды.", "group": "Фильтр"},
            {"flag": "-k", "label": "Игнор TLS-ошибок", "type": "bool", "description": "Не проверять сертификат.", "group": "Соединение"},
            {"flag": "-r", "label": "Идти по редиректам", "type": "bool", "description": "Следовать 30x.", "group": "Соединение"},
            {"flag": "-q", "label": "Тихо (-q)", "type": "bool", "default": "on", "description": "Без баннера.", "group": "Вывод"},
            {"flag": "--no-color", "label": "Без цвета", "type": "bool", "default": "on", "description": "Отключить ANSI-цвета.", "group": "Вывод"},
        ],
    },
    {
        "id": "ffuf",
        "name": "ffuf",
        "binary": "ffuf",
        "category": "dirs",
        "description": "Быстрый веб-фаззер (маркер FUZZ).",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site/FUZZ"},
        "examples": ["ffuf -u https://site/FUZZ -w list.txt -mc 200,301 -t 40"],
        "flags": [
            {"flag": "-w", "label": "Словарь", "type": "text", "placeholder": "/usr/share/wordlists/dirb/common.txt", "description": "Файл словаря (можно list.txt:FUZZ).", "group": "Словарь"},
            {"flag": "-mc", "label": "Коды совпадений", "type": "text", "placeholder": "200,204,301,302,307,401,403", "description": "Показывать эти статусы.", "group": "Фильтр"},
            {"flag": "-fc", "label": "Скрыть коды", "type": "text", "placeholder": "404", "description": "Прятать эти статусы.", "group": "Фильтр"},
            {"flag": "-fs", "label": "Скрыть по размеру", "type": "text", "placeholder": "0,1234", "description": "Прятать ответы такого размера.", "group": "Фильтр"},
            {"flag": "-t", "label": "Потоки", "type": "number", "placeholder": "40", "default": "40", "description": "Параллелизм.", "group": "Производительность"},
            {"flag": "-recursion", "label": "Рекурсия", "type": "bool", "description": "Углубляться в найденные каталоги.", "group": "Область"},
            {"flag": "-H", "label": "Заголовок", "type": "text", "placeholder": "Authorization: Bearer ...", "description": "Доп. HTTP-заголовок.", "group": "Запрос"},
            {"flag": "-s", "label": "Тихо (-s)", "type": "bool", "default": "on", "description": "Только результаты.", "group": "Вывод"},
        ],
    },
    {
        "id": "whatweb",
        "name": "whatweb",
        "binary": "whatweb",
        "category": "recon",
        "description": "Определение технологий и CMS сайта.",
        "target": {"kind": "url", "flag": "", "placeholder": "https://site"},
        "examples": ["whatweb -a 3 https://site"],
        "flags": [
            {"flag": "-a", "label": "Агрессивность", "type": "choice", "choices": ["1", "3", "4"], "default": "1", "description": "1 пассивно … 4 агрессивно.", "group": "Обнаружение"},
            {"flag": "-v", "label": "Подробно", "type": "bool", "description": "Развёрнутый вывод.", "group": "Вывод"},
            {"flag": "--no-errors", "label": "Скрыть ошибки", "type": "bool", "description": "Не печатать ошибки соединения.", "group": "Вывод"},
            {"flag": "--color=never", "label": "Без цвета", "type": "bool", "default": "on", "description": "Отключить ANSI.", "group": "Вывод"},
        ],
    },
    {
        "id": "nuclei",
        "name": "nuclei",
        "binary": "nuclei",
        "category": "web_vuln",
        "description": "Шаблонный сканер уязвимостей и мисконфигураций.",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site"},
        "examples": ["nuclei -u https://site -severity medium,high,critical -silent"],
        "flags": [
            {"flag": "-severity", "label": "Критичность", "type": "text", "placeholder": "low,medium,high,critical", "description": "Фильтр по severity.", "group": "Фильтр"},
            {"flag": "-tags", "label": "Теги", "type": "text", "placeholder": "cve, exposure, tech", "description": "Ограничить набор шаблонов тегами.", "group": "Фильтр"},
            {"flag": "-rl", "label": "Лимит запросов/с", "type": "number", "placeholder": "150", "description": "Rate limit.", "group": "Производительность"},
            {"flag": "-c", "label": "Параллелизм", "type": "number", "placeholder": "25", "description": "Одновременных шаблонов.", "group": "Производительность"},
            {"flag": "-silent", "label": "Тихо", "type": "bool", "default": "on", "description": "Только находки.", "group": "Вывод"},
            {"flag": "-nc", "label": "Без цвета", "type": "bool", "default": "on", "description": "Отключить ANSI.", "group": "Вывод"},
        ],
    },
    {
        "id": "sslscan",
        "name": "sslscan",
        "binary": "sslscan",
        "category": "tls",
        "description": "Поддерживаемые протоколы/шифры TLS, слабые наборы.",
        "target": {"kind": "host", "flag": "", "placeholder": "host:443"},
        "examples": ["sslscan --no-colour host:443"],
        "flags": [
            {"flag": "--no-colour", "label": "Без цвета", "type": "bool", "default": "on", "description": "Отключить ANSI.", "group": "Вывод"},
            {"flag": "--show-certificate", "label": "Показать сертификат", "type": "bool", "description": "Полные данные сертификата.", "group": "Вывод"},
            {"flag": "--starttls-smtp", "label": "STARTTLS SMTP", "type": "bool", "description": "Согласовать TLS по SMTP.", "group": "Режим"},
            {"flag": "--starttls-ftp", "label": "STARTTLS FTP", "type": "bool", "description": "Согласовать TLS по FTP.", "group": "Режим"},
        ],
    },
    {
        "id": "dig",
        "name": "dig",
        "binary": "dig",
        "category": "recon",
        "description": "DNS-запросы: записи, зона, обратные.",
        "target": {"kind": "host", "flag": "", "placeholder": "example.com"},
        "examples": ["dig example.com ANY +noall +answer", "dig @8.8.8.8 example.com MX"],
        "flags": [
            {"flag": "ANY", "label": "Тип: ANY", "type": "bool", "description": "Все записи.", "group": "Тип записи"},
            {"flag": "A", "label": "Тип: A", "type": "bool", "description": "IPv4-адрес.", "group": "Тип записи"},
            {"flag": "AAAA", "label": "Тип: AAAA", "type": "bool", "description": "IPv6-адрес.", "group": "Тип записи"},
            {"flag": "MX", "label": "Тип: MX", "type": "bool", "description": "Почтовые серверы.", "group": "Тип записи"},
            {"flag": "NS", "label": "Тип: NS", "type": "bool", "description": "DNS-серверы зоны.", "group": "Тип записи"},
            {"flag": "TXT", "label": "Тип: TXT", "type": "bool", "description": "Текстовые записи (SPF/DKIM).", "group": "Тип записи"},
            {"flag": "+short", "label": "+short", "type": "bool", "description": "Кратко.", "group": "Вывод"},
            {"flag": "+noall +answer", "label": "Только ответ", "type": "bool", "description": "Убрать служебные секции.", "group": "Вывод"},
            {"flag": "+trace", "label": "+trace", "type": "bool", "description": "Пошаговое разрешение от корня.", "group": "Вывод"},
        ],
    },
    {
        "id": "curl",
        "name": "curl",
        "binary": "curl",
        "category": "recon",
        "description": "HTTP-запросы вручную: заголовки, методы, тело.",
        "target": {"kind": "url", "flag": "", "placeholder": "https://site"},
        "examples": ["curl -sSIL https://site", "curl -sS -X POST -d 'a=1' https://site/api"],
        "flags": [
            {"flag": "-I", "label": "Только заголовки (-I)", "type": "bool", "description": "HEAD-запрос.", "group": "Метод"},
            {"flag": "-X", "label": "Метод", "type": "text", "placeholder": "POST", "description": "HTTP-метод.", "group": "Метод"},
            {"flag": "-d", "label": "Тело", "type": "text", "placeholder": "a=1&b=2", "description": "Данные POST.", "group": "Запрос"},
            {"flag": "-H", "label": "Заголовок", "type": "text", "placeholder": "Authorization: Bearer ...", "description": "Доп. заголовок.", "group": "Запрос"},
            {"flag": "-L", "label": "По редиректам (-L)", "type": "bool", "description": "Следовать 30x.", "group": "Поведение"},
            {"flag": "-k", "label": "Игнор TLS (-k)", "type": "bool", "description": "Не проверять сертификат.", "group": "Поведение"},
            {"flag": "-A", "label": "User-Agent", "type": "text", "placeholder": "Mozilla/5.0 ...", "description": "Заголовок User-Agent.", "group": "Запрос"},
            {"flag": "--max-time", "label": "Таймаут", "type": "number", "placeholder": "20", "description": "Максимум секунд.", "group": "Поведение"},
            {"flag": "-s", "label": "Тихо (-s)", "type": "bool", "default": "on", "description": "Без прогресс-бара.", "group": "Вывод"},
        ],
    },
    {
        "id": "wpscan",
        "name": "wpscan",
        "binary": "wpscan",
        "category": "web_vuln",
        "description": "Сканер WordPress: версия ядра, уязвимые плагины/темы, пользователи.",
        "target": {"kind": "url", "flag": "--url", "placeholder": "https://blog"},
        "examples": ["wpscan --url https://blog --enumerate vp,vt,u --random-user-agent"],
        "flags": [
            {"flag": "--enumerate", "label": "Что перечислять", "type": "text", "placeholder": "vp,vt,u,ap", "description": "vp=уязв. плагины, vt=уязв. темы, u=пользователи, ap=все плагины.", "group": "Перечисление"},
            {"flag": "--api-token", "label": "WPVulnDB токен", "type": "text", "placeholder": "xxxxxxxx", "description": "Токен базы уязвимостей для детальных данных.", "group": "Данные"},
            {"flag": "--plugins-detection", "label": "Детект плагинов", "type": "choice", "choices": ["passive", "mixed", "aggressive"], "description": "Способ обнаружения плагинов.", "group": "Перечисление"},
            {"flag": "--random-user-agent", "label": "Случайный UA", "type": "bool", "default": "on", "description": "Менять User-Agent между запросами.", "group": "Обход"},
            {"flag": "--force", "label": "Игнор 'не WP'", "type": "bool", "description": "Сканировать, даже если WordPress не подтверждён.", "group": "Обход"},
            {"flag": "--disable-tls-checks", "label": "Игнор TLS", "type": "bool", "description": "Не проверять сертификат.", "group": "Обход"},
        ],
    },
    {
        "id": "subfinder",
        "name": "subfinder",
        "binary": "subfinder",
        "category": "osint",
        "description": "Пассивный сбор поддоменов из множества источников.",
        "target": {"kind": "host", "flag": "-d", "placeholder": "example.com"},
        "examples": ["subfinder -d example.com -all -silent"],
        "flags": [
            {"flag": "-all", "label": "Все источники", "type": "bool", "description": "Задействовать все доступные пассивные источники (медленнее).", "group": "Источники"},
            {"flag": "-recursive", "label": "Рекурсивно", "type": "bool", "description": "Рекурсивный поиск поддоменов поддоменов.", "group": "Область"},
            {"flag": "-silent", "label": "Только результат", "type": "bool", "default": "on", "description": "Без баннера и статистики.", "group": "Вывод"},
            {"flag": "-nW", "label": "Только рабочие", "type": "bool", "description": "Отбрасывать неразрешаемые имена.", "group": "Фильтр"},
        ],
    },
    {
        "id": "httpx",
        "name": "httpx",
        "binary": "httpx",
        "category": "recon",
        "description": "Быстрый HTTP-пробинг: живые хосты, коды, заголовки, технологии.",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site или host"},
        "examples": ["httpx -u example.com -sc -title -tech-detect -web-server -silent"],
        "flags": [
            {"flag": "-sc", "label": "Код ответа", "type": "bool", "default": "on", "description": "Показывать HTTP-статус.", "group": "Что показать"},
            {"flag": "-title", "label": "Title", "type": "bool", "default": "on", "description": "Извлекать <title>.", "group": "Что показать"},
            {"flag": "-tech-detect", "label": "Технологии", "type": "bool", "default": "on", "description": "Определять стек (Wappalyzer).", "group": "Что показать"},
            {"flag": "-web-server", "label": "Сервер", "type": "bool", "description": "Заголовок Server.", "group": "Что показать"},
            {"flag": "-ip", "label": "IP", "type": "bool", "description": "Резолвить IP.", "group": "Что показать"},
            {"flag": "-follow-redirects", "label": "По редиректам", "type": "bool", "description": "Идти по 30x.", "group": "Поведение"},
            {"flag": "-mc", "label": "Коды совпадений", "type": "text", "placeholder": "200,301,403", "description": "Показывать только эти статусы.", "group": "Фильтр"},
            {"flag": "-silent", "label": "Тихо", "type": "bool", "default": "on", "description": "Без служебного вывода.", "group": "Вывод"},
        ],
    },
    {
        "id": "dnsx",
        "name": "dnsx",
        "binary": "dnsx",
        "category": "recon",
        "description": "Массовый DNS-резолвер: A/AAAA/CNAME/MX/NS/TXT, PTR, wildcard.",
        "target": {"kind": "host", "flag": "-d", "placeholder": "example.com"},
        "examples": ["dnsx -d example.com -a -resp -silent"],
        "flags": [
            {"flag": "-a", "label": "A", "type": "bool", "default": "on", "description": "IPv4-записи.", "group": "Типы"},
            {"flag": "-aaaa", "label": "AAAA", "type": "bool", "description": "IPv6-записи.", "group": "Типы"},
            {"flag": "-cname", "label": "CNAME", "type": "bool", "description": "Канонические имена.", "group": "Типы"},
            {"flag": "-mx", "label": "MX", "type": "bool", "description": "Почтовые серверы.", "group": "Типы"},
            {"flag": "-ns", "label": "NS", "type": "bool", "description": "DNS-серверы.", "group": "Типы"},
            {"flag": "-txt", "label": "TXT", "type": "bool", "description": "Текстовые записи.", "group": "Типы"},
            {"flag": "-ptr", "label": "PTR", "type": "bool", "description": "Обратные записи.", "group": "Типы"},
            {"flag": "-resp", "label": "Показать значения", "type": "bool", "default": "on", "description": "Печатать содержимое записей.", "group": "Вывод"},
            {"flag": "-silent", "label": "Тихо", "type": "bool", "default": "on", "description": "Без баннера.", "group": "Вывод"},
        ],
    },
    {
        "id": "dnsrecon",
        "name": "dnsrecon",
        "binary": "dnsrecon",
        "category": "recon",
        "description": "DNS-разведка: стандартные записи, AXFR, обратные зоны, брутфорс.",
        "target": {"kind": "host", "flag": "-d", "placeholder": "example.com"},
        "examples": ["dnsrecon -d example.com -t std,axfr"],
        "flags": [
            {"flag": "-t", "label": "Типы разведки", "type": "text", "placeholder": "std,axfr,brt,rvl,srv", "description": "std=обычные, axfr=трансфер зоны, brt=брутфорс, rvl=обратные, srv=SRV.", "group": "Режим"},
            {"flag": "-D", "label": "Словарь (brt)", "type": "text", "placeholder": "/usr/share/wordlists/...", "description": "Словарь имён для -t brt.", "group": "Режим"},
            {"flag": "-n", "label": "Nameserver", "type": "text", "placeholder": "8.8.8.8", "description": "Использовать конкретный DNS-сервер.", "group": "Соединение"},
            {"flag": "-a", "label": "AXFR", "type": "bool", "description": "Попытка трансфера зоны со всех NS.", "group": "Режим"},
        ],
    },
    {
        "id": "feroxbuster",
        "name": "feroxbuster",
        "binary": "feroxbuster",
        "category": "dirs",
        "description": "Рекурсивный перебор путей на Rust — быстрый, с авто-углублением.",
        "target": {"kind": "url", "flag": "-u", "placeholder": "https://site"},
        "examples": ["feroxbuster -u https://site -w common.txt -x php,txt -d 2"],
        "flags": [
            {"flag": "-w", "label": "Словарь", "type": "text", "placeholder": "/usr/share/dirb/wordlists/common.txt", "description": "Файл словаря.", "group": "Словарь"},
            {"flag": "-x", "label": "Расширения", "type": "text", "placeholder": "php,txt,bak", "description": "Проверять с расширениями.", "group": "Словарь"},
            {"flag": "-d", "label": "Глубина", "type": "number", "placeholder": "2", "description": "Глубина рекурсии (0 = без лимита).", "group": "Область"},
            {"flag": "-t", "label": "Потоки", "type": "number", "placeholder": "50", "description": "Число потоков.", "group": "Производительность"},
            {"flag": "-s", "label": "Показать коды", "type": "text", "placeholder": "200,301,302,401,403", "description": "Белый список статусов.", "group": "Фильтр"},
            {"flag": "-C", "label": "Скрыть коды", "type": "text", "placeholder": "404,500", "description": "Чёрный список статусов.", "group": "Фильтр"},
            {"flag": "-k", "label": "Игнор TLS", "type": "bool", "description": "Не проверять сертификат.", "group": "Соединение"},
            {"flag": "--silent", "label": "Тихо", "type": "bool", "default": "on", "description": "Минимальный вывод.", "group": "Вывод"},
        ],
    },
    {
        "id": "dalfox",
        "name": "dalfox",
        "binary": "dalfox",
        "category": "web_vuln",
        "description": "Сканер XSS: анализ параметров, DOM, обход фильтров, PoC.",
        "target": {"kind": "url", "flag": "url", "placeholder": "https://site/search?q=1"},
        "examples": ["dalfox url \"https://site/search?q=FUZZ\" --deep-domxss"],
        "flags": [
            {"flag": "--deep-domxss", "label": "Глубокий DOM XSS", "type": "bool", "description": "Тщательный анализ DOM-based XSS.", "group": "Обнаружение"},
            {"flag": "--mining-dom", "label": "Майнинг параметров DOM", "type": "bool", "default": "on", "description": "Искать параметры в DOM.", "group": "Обнаружение"},
            {"flag": "-b", "label": "Blind XSS callback", "type": "text", "placeholder": "https://your.xss.ht", "description": "URL для слепого XSS.", "group": "Обнаружение"},
            {"flag": "--custom-payload", "label": "Свои нагрузки", "type": "text", "placeholder": "payloads.txt", "description": "Файл с пользовательскими нагрузками.", "group": "Нагрузки"},
            {"flag": "--cookie", "label": "Cookie", "type": "text", "placeholder": "SES= ...", "description": "Заголовок Cookie.", "group": "Запрос"},
            {"flag": "--worker", "label": "Потоки", "type": "number", "placeholder": "100", "description": "Число воркеров.", "group": "Производительность"},
            {"flag": "--silence", "label": "Тихо", "type": "bool", "default": "on", "description": "Только находки.", "group": "Вывод"},
        ],
    },
    {
        "id": "amass",
        "name": "amass (enum)",
        "binary": "amass",
        "category": "osint",
        "description": "Глубокое картирование поверхности атаки по доменам.",
        "target": {"kind": "host", "flag": "-d", "placeholder": "example.com", "prefix_subcommand": "enum"},
        "examples": ["amass enum -passive -d example.com -timeout 10"],
        "flags": [
            {"flag": "-passive", "label": "Пассивно", "type": "bool", "default": "on", "description": "Только открытые источники, без запросов к цели.", "group": "Режим"},
            {"flag": "-active", "label": "Активно", "type": "bool", "description": "Резолв, попытки трансфера зоны, захват сертификатов.", "group": "Режим"},
            {"flag": "-brute", "label": "Брутфорс имён", "type": "bool", "description": "Перебор поддоменов по словарю.", "group": "Режим"},
            {"flag": "-timeout", "label": "Таймаут (мин)", "type": "number", "placeholder": "10", "description": "Ограничение времени работы.", "group": "Ограничения"},
        ],
    },
    {
        "id": "theHarvester",
        "name": "theHarvester",
        "binary": "theHarvester",
        "category": "osint",
        "description": "Сбор e-mail, имён, поддоменов и хостов из открытых источников.",
        "target": {"kind": "host", "flag": "-d", "placeholder": "example.com"},
        "examples": ["theHarvester -d example.com -b bing,crtsh,duckduckgo -l 500"],
        "flags": [
            {"flag": "-b", "label": "Источники", "type": "text", "placeholder": "bing,crtsh,duckduckgo,otx", "description": "Список источников (или 'all').", "group": "Источники"},
            {"flag": "-l", "label": "Лимит результатов", "type": "number", "placeholder": "500", "description": "Сколько результатов запрашивать.", "group": "Ограничения"},
            {"flag": "-s", "label": "Старт со смещения", "type": "number", "placeholder": "0", "description": "Смещение выборки.", "group": "Ограничения"},
            {"flag": "--dns-lookup", "label": "DNS-резолв", "type": "bool", "description": "Резолвить найденные хосты.", "group": "Обработка"},
        ],
    },
    {
        "id": "masscan",
        "name": "masscan",
        "binary": "masscan",
        "category": "network",
        "description": "Очень быстрый сканер портов (собственный TCP/IP-стек).",
        "target": {"kind": "host", "flag": "", "placeholder": "10.0.0.0/24"},
        "examples": ["masscan 10.0.0.0/24 -p80,443,8080 --rate 2000"],
        "flags": [
            {"flag": "-p", "label": "Порты", "type": "text", "placeholder": "80,443,1-1000 или U:53", "description": "Список/диапазоны портов.", "group": "Область"},
            {"flag": "--rate", "label": "Пакетов/с", "type": "number", "placeholder": "1000", "description": "Скорость отправки (осторожно с сетью!).", "group": "Производительность"},
            {"flag": "--banners", "label": "Баннеры", "type": "bool", "description": "Пытаться снять баннеры сервисов.", "group": "Определение"},
            {"flag": "--ping", "label": "ICMP ping", "type": "bool", "description": "Включить ICMP-обнаружение.", "group": "Область"},
            {"flag": "--open-only", "label": "Только открытые", "type": "bool", "default": "on", "description": "Не печатать закрытые.", "group": "Вывод"},
        ],
    },
    {
        "id": "hydra",
        "name": "hydra",
        "binary": "hydra",
        "category": "brute",
        "description": "Онлайн-перебор паролей для множества протоколов.",
        "target": {"kind": "host", "flag": "", "placeholder": "10.0.0.5 ssh"},
        "examples": ["hydra -l admin -P rockyou.txt -t 4 -f 10.0.0.5 ssh"],
        "flags": [
            {"flag": "-l", "label": "Логин", "type": "text", "placeholder": "admin", "description": "Один логин.", "group": "Учётные данные"},
            {"flag": "-L", "label": "Файл логинов", "type": "text", "placeholder": "users.txt", "description": "Список логинов.", "group": "Учётные данные"},
            {"flag": "-p", "label": "Пароль", "type": "text", "placeholder": "password", "description": "Один пароль.", "group": "Учётные данные"},
            {"flag": "-P", "label": "Файл паролей", "type": "text", "placeholder": "/usr/share/wordlists/rockyou.txt", "description": "Список паролей.", "group": "Учётные данные"},
            {"flag": "-s", "label": "Порт", "type": "number", "placeholder": "22", "description": "Нестандартный порт сервиса.", "group": "Соединение"},
            {"flag": "-t", "label": "Параллельно", "type": "number", "placeholder": "4", "default": "4", "description": "Число задач (SSH — не больше 4).", "group": "Производительность"},
            {"flag": "-f", "label": "Стоп при успехе", "type": "bool", "default": "on", "description": "Завершить после первой пары.", "group": "Поведение"},
            {"flag": "-V", "label": "Подробно", "type": "bool", "description": "Показывать каждую попытку.", "group": "Вывод"},
        ],
    },
    {
        "id": "sslyze",
        "name": "sslyze",
        "binary": "sslyze",
        "category": "tls",
        "description": "Анализ конфигурации TLS: наборы шифров, уязвимости, сертификат.",
        "target": {"kind": "host", "flag": "", "placeholder": "host:443"},
        "examples": ["sslyze --mozilla_config=intermediate host:443"],
        "flags": [
            {"flag": "--mozilla_config=intermediate", "label": "Профиль Mozilla", "type": "bool", "description": "Сверить с рекомендациями Mozilla (intermediate).", "group": "Проверки"},
            {"flag": "--certinfo", "label": "Сертификат", "type": "bool", "default": "on", "description": "Полный анализ цепочки сертификатов.", "group": "Проверки"},
            {"flag": "--heartbleed", "label": "Heartbleed", "type": "bool", "description": "Проверка CVE-2014-0160.", "group": "Уязвимости"},
            {"flag": "--robot", "label": "ROBOT", "type": "bool", "description": "Проверка атаки ROBOT.", "group": "Уязвимости"},
            {"flag": "--reneg", "label": "Renegotiation", "type": "bool", "description": "Небезопасное пересогласование.", "group": "Уязвимости"},
            {"flag": "--compression", "label": "CRIME", "type": "bool", "description": "TLS-компрессия (CRIME).", "group": "Уязвимости"},
        ],
    },
    {
        "id": "smbmap",
        "name": "smbmap",
        "binary": "smbmap",
        "category": "network",
        "description": "Перечисление SMB-ресурсов и прав доступа.",
        "target": {"kind": "host", "flag": "-H", "placeholder": "10.0.0.5"},
        "examples": ["smbmap -H 10.0.0.5 -u guest -p '' -R"],
        "flags": [
            {"flag": "-u", "label": "Пользователь", "type": "text", "placeholder": "guest", "description": "Имя пользователя.", "group": "Аутентификация"},
            {"flag": "-p", "label": "Пароль/хэш", "type": "text", "placeholder": "'' или пароль", "description": "Пароль или NTLM-хэш.", "group": "Аутентификация"},
            {"flag": "-d", "label": "Домен", "type": "text", "placeholder": "WORKGROUP", "description": "Домен/рабочая группа.", "group": "Аутентификация"},
            {"flag": "-R", "label": "Рекурсивно", "type": "text", "placeholder": "ShareName", "description": "Рекурсивный листинг шары.", "group": "Область"},
            {"flag": "-x", "label": "Команда", "type": "text", "placeholder": "ipconfig /all", "description": "Выполнить команду (нужны права).", "group": "Действия"},
        ],
    },
    {
        "id": "wafw00f",
        "name": "wafw00f",
        "binary": "wafw00f",
        "category": "recon",
        "description": "Определение WAF/IPS перед веб-приложением.",
        "target": {"kind": "url", "flag": "", "placeholder": "https://site"},
        "examples": ["wafw00f -a https://site"],
        "flags": [
            {"flag": "-a", "label": "Найти все WAF", "type": "bool", "default": "on", "description": "Не останавливаться на первом совпадении.", "group": "Режим"},
            {"flag": "-v", "label": "Подробно", "type": "bool", "description": "Развёрнутый вывод.", "group": "Вывод"},
        ],
    },
]
